# Generated by Django 6.0.3 on 2026-05-02 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0005_labelhistory"),
        ("examples", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fragment",
            name="parent_fragment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_fragments",
                to="examples.fragment",
            ),
        ),
        migrations.AddField(
            model_name="fragment",
            name="sequence_group",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="fragment",
            name="sequence_order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fragment",
            name="character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fragments",
                to="characters.basecard",
            ),
        ),
    ]
