# Generated by Django 6.0.3 on 2026-05-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0002_fragment_parent_fragment_fragment_sequence_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fragment",
            name="end_line",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fragment",
            name="fragment_type",
            field=models.CharField(
                choices=[("story", "Story"), ("skip", "Skip")],
                default="story",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="fragment",
            name="start_line",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
