# Generated by Django 6.0.3 on 2026-04-02 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLLMConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("anthropic", "Anthropic (Claude)"),
                            ("gemini", "Google (Gemini)"),
                        ],
                        default="anthropic",
                        max_length=20,
                    ),
                ),
                ("api_key_encrypted", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
