# Generated by Django 6.0.3 on 2026-05-01 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def migrate_existing_keys(apps, schema_editor):
        UserLLMConfig = apps.get_model('users', 'UserLLMConfig')
        UserProviderKey = apps.get_model('users', 'UserProviderKey')
        for config in UserLLMConfig.objects.all():
            if hasattr(config, 'api_key_encrypted') and config.api_key_encrypted:
                UserProviderKey.objects.get_or_create(
                    user=config.user,
                    provider=config.provider,
                    defaults={'api_key_encrypted': config.api_key_encrypted},
                )

    operations = [
        migrations.RemoveField(
            model_name="userllmconfig",
            name="api_key_encrypted",
        ),
        migrations.RemoveField(
            model_name="userllmconfig",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userllmconfig",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="userllmconfig",
            name="provider",
            field=models.CharField(default="gemini", max_length=20),
        ),
        migrations.CreateModel(
            name="UserProviderKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("api_key_encrypted", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "provider")},
            },
        ),
        migrations.RunPython(migrate_existing_keys, migrations.RunPython.noop),
    ]

