[project]
name = "fanfic-assistant-backend"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
  "anthropic==0.40.0",
  "asgiref==3.11.1",
  "cryptography==44.0.0",
  "dj-database-url==3.1.2",
  "django==6.0.3",
  "django-cors-headers==4.9.0",
  "djangorestframework==3.17.0",
  "djangorestframework-camel-case==1.4.2",
  "djangorestframework-simplejwt==5.5.1",
  "drf-nested-routers==0.95.0",
  "google-genai==1.0.0",
  "groq==1.7.0",
  "gunicorn==25.1.0",
  "openai==3.24.0",
  "packaging==26.0",
  "pgvector==0.5.0",
  "psycopg2-binary==2.9.11",
  "pyjwt==2.12.1",
  "python-dotenv==1.2.2",
  "sqlparse==0.5.5",
  "tzdata==2025.3",
  "whitenoise==6.12.0",
]

[dependency-groups]
dev = [
  "factory-boy==3.3.1",
  "pytest==8.3.4",
  "pytest-cov==6.0.0",
  "pytest-django==4.9.0",
]

[tool.uv]
package = false
