# Generated by Django 6.0.3 on 2026-03-19 02:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("fandom", models.CharField(blank=True, max_length=200)),
                ("card_author", models.CharField(blank=True, max_length=100)),
                ("version", models.CharField(default="v1.0", max_length=20)),
                ("author_nicknames", models.JSONField(blank=True, default=list)),
                ("mbti", models.CharField(blank=True, max_length=4)),
                ("mbti_notes", models.TextField(blank=True)),
                ("core_values", models.JSONField(blank=True, default=list)),
                ("core_fears", models.JSONField(blank=True, default=list)),
                ("key_experiences", models.JSONField(blank=True, default=list)),
                ("quick_labels", models.JSONField(blank=True, default=list)),
                ("behavioral_patterns", models.JSONField(blank=True, default=list)),
                ("forbidden_behaviors", models.JSONField(blank=True, default=list)),
                ("default_state", models.TextField(blank=True)),
                ("emotional_triggers", models.JSONField(blank=True, default=list)),
                ("emotion_expression_style", models.TextField(blank=True)),
                ("recovery_pattern", models.TextField(blank=True)),
                ("conditions", models.JSONField(blank=True, default=list)),
                ("physical_traits", models.JSONField(blank=True, default=list)),
                (
                    "speech_style_custom_tags",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AUMod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("au_name", models.CharField(max_length=200)),
                ("setting", models.TextField(blank=True)),
                ("role_title", models.CharField(blank=True, max_length=200)),
                ("role_age", models.CharField(blank=True, max_length=50)),
                ("role_current_situation", models.TextField(blank=True)),
                ("quick_labels", models.JSONField(blank=True, default=list)),
                ("forbidden_behaviors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="au_mods",
                        to="characters.basecard",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
