# Generated by Django 6.0.3 on 2026-04-01 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aumod",
            name="inherit_exclude",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_tone",
                    models.TextField(
                        blank=True, help_text="关系整体基调，客观描述，不预设视角"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="用于访问控制，不代表关系从属于该用户之外的某个角色",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RelationshipMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nicknames_for_others", models.JSONField(blank=True, default=list)),
                ("quick_labels", models.JSONField(blank=True, default=list)),
                ("forbidden_behaviors", models.JSONField(blank=True, default=list)),
                ("inherit_exclude", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="characters.basecard",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="characters.relationship",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("relationship", "character")},
            },
        ),
        migrations.AddField(
            model_name="relationship",
            name="participants",
            field=models.ManyToManyField(
                related_name="relationships",
                through="characters.RelationshipMembership",
                to="characters.basecard",
            ),
        ),
    ]
