# Generated by Django 6.0.3 on 2026-04-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0002_aumod_inherit_exclude_relationship_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basecard",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "男"), ("female", "女"), ("other", "其他")],
                max_length=10,
            ),
        ),
    ]
