# Generated by Django 6.0.3 on 2026-04-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0003_basecard_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="basecard",
            name="gender_pronoun",
            field=models.CharField(
                blank=True,
                help_text="仅 gender=other 时填写，例：他们、TA、祂们",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="basecard",
            name="gender_type",
            field=models.CharField(
                blank=True,
                help_text="仅 gender=other 时填写，例：双性、无性别、流性别",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="basecard",
            name="gender",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
