# Generated by Django 6.0.3 on 2026-04-01 21:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LlmCallLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_id", models.UUIDField(db_index=True, null=True)),
                ("feature", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=64)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("latency_ms", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("error", "Error")],
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="logs_llmcal_created_911a8e_idx"
                    ),
                    models.Index(
                        fields=["feature", "status"],
                        name="logs_llmcal_feature_6ae80c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RestApiLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_id", models.UUIDField(db_index=True)),
                ("method", models.CharField(max_length=8)),
                ("path", models.CharField(max_length=256)),
                ("status_code", models.IntegerField()),
                ("latency_ms", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="logs_restap_created_d77b0d_idx"
                    ),
                    models.Index(
                        fields=["path", "status_code"],
                        name="logs_restap_path_373636_idx",
                    ),
                ],
            },
        ),
    ]
