# Generated by Django 6.0.3 on 2026-04-08 03:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="llmcalllog",
            name="generation_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="llmcalllog",
            index=models.Index(
                fields=["generation_id"], name="logs_llmcal_generat_da55f5_idx"
            ),
        ),
    ]
