# Generated by Django 6.0.3 on 2026-10-06 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_vectorsearchlog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='llmcalllog',
            name='logs_llmcal_generat_da55f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='vectorsearchlog',
            name='logs_vector_gen_id_idx',
        ),
    ]
